[package]
name = "mensa-upb-scraper"
description = "A web scraper for the canteens of the University of Paderborn"
license.workspace = true
authors.workspace = true
repository.workspace = true
readme.workspace = true
version = "0.2.1"
edition = "2024"
publish = false

[[bin]]
name = "scraper-cli"
path = "src/bin/cli.rs"

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
clap = { version = "4.5.54", features = ["derive", "env"] }
dotenvy = { workspace = true }
extend = "1.2.0"
futures = { workspace = true }
html-escape = "0.2.13"
itertools = { workspace = true }
lazy-regex = "3.6.0"
reqwest = { version = "0.12.9", default-features = false, features = ["charset", "json", "rustls-tls", "http2"] }
serde = { workspace = true, features = ["derive"] }
shared = { path = "../shared" }
sqlx = { workspace = true, features = ["runtime-tokio-rustls", "postgres", "migrate", "chrono", "uuid", "rust_decimal"] }
strum = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["fmt", "std", "env-filter", "registry", "json", "tracing-log"] }
